# action.yml
name: 'Send Workflow Logs to Splunk'
description: 'Upload GitHub Workflow logs to Splunk HEC'
inputs:
  splunk_url:
    description: 'Full URL for Splunk HEC endpoint'
    required: true
  hec_token:
    description: 'Splunk HEC Token'
    required: true
  github_token:
    description: 'Github PAT'
    required: true
  sourcetype:
    description: 'Splunk Sourcetype'
    default: 'github_workflow_log_action'
  source:
    description: 'GitHub Workflow name'
    default: ${{ github.workflow }}
  workflow_id:
    description: 'The Workflow Run number'
    default: ${{ github.run_number}}
outputs:
  status:
    description: 'value is success/fail based on POST result'
runs:
  using: 'docker'
  image: 'Dockerfile'
