name: Validate and Run Commands Based on PR Labels

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  validate-and-execute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR Labels
        id: get-labels
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            return labels;
          result-encoding: string
