name: Send Workflow Logs to Splunk

# Controls when the action will run.
on:
  workflow_dispatch:

jobs:
  WriteLogs:
    runs-on: ubuntu-latest

    steps:
      - name: Send Workflow logs to Splunk
        uses: ykoer/github-workflow-splunk-logger@dev
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          splunk_url: ${{ vars.HEC_URL }}
          splunk_token: ${{ secrets.HEC_TOKEN }}
          run_id: 13309230902
        