name: Send Workflow Logs to Splunk

# Controls when the action will run.
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["*"]
    types:
      - completed

env:
  triggerID: ${{ github.event.workflow_run.id }}
  triggerJob: ${{ github.event.workflow_run.name }}

jobs:
  WriteLogs:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.name!='WriteLogs'}}

    steps:
      - name: Debug Workflow Information
        run: |
          echo "Trigger ID: ${{ env.triggerID }}"
          echo "Trigger Job: ${{ env.triggerJob }}"
          echo "Event type: ${{ github.event_name }}"
          echo "Workflow ID that triggered this: ${{ github.event.workflow_run.id }}"
          echo "Workflow Name that triggered this: ${{ github.event.workflow_run.name }}"
          echo "Workflow file: ${{ github.event.workflow_run.path }}"

      - uses: actions/checkout@v2

      - name: Output Job ID
        run: echo ${{ github.event.workflow_run.id }}

      - name: Send Workflow logs to Splunk
        if: ${{ always() }}
        uses: ./.github/actions/log_to_splunk
        with:
          splunk_url: ${{ vars.HEC_URL }}
          hec_token: ${{ secrets.HEC_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_id: ${{ env.triggerID }}
          source: ${{ env.triggerJob }}